/**
 * Link DOL filing rows to companies, then use FEIN to repair LCA's linkage.
 *
 * THE PROBLEM. perm_records.company_id and pwd_records.company_id are unpopulated, and
 * lca_records is only 17.6% linked (128,188 of 728,993). That is why lib/h1b/transfer-velocity.ts
 * and lib/h1b/placement-graph.ts aggregate on employer_name_normalized instead of company_id —
 * keying on company_id would have hidden ~97% of the signal. Linking properly lets those surfaces
 * join to real companies (logo, domain, live jobs) instead of a bare employer string.
 *
 * WHY NAME AND NOT FEIN FIRST. A FEIN bridge sounds better — FEIN is 100% filled and unambiguous —
 * but it has to be bootstrapped from rows that are ALREADY linked, and LCA's linkage is the thing
 * that is broken. Measured: FEIN-bridging PERM yields 10,752 rows, name-joining yields 89,993.
 * So: name-link PERM/PWD first, then use the FEIN map that falls out to fix LCA.
 *
 * ⚠ JOIN THROUGH company_name_norm(), never by equating the stored *_normalized columns.
 * companies.name_normalized is generated by the SQL company_name_norm(); the DOL tables use the
 * TypeScript normalizeEmployerName(). They disagree ('amazon com services' vs 'amazon com').
 *
 * ⚠ AMBIGUITY IS REAL: 1,780 of 5,040 PERM employer names match MORE THAN ONE company row (our
 * duplicate-companies problem). Ties are broken deterministically — canonical over duplicate,
 * active over inactive, more jobs over fewer, real domain over harvester placeholder, then oldest.
 *
 * ⚠ PROPAGATION AMPLIFIES ERRORS. A bad name match currently mis-states one employer panel; once
 * it flows through FEIN it can mis-label hundreds of LCA rows. So --propagate-lca only uses FEINs
 * that resolve to exactly ONE company, which is a far stronger guard than any name-length rule.
 *
 *   npx tsx scripts/link-employers-to-companies.ts                     # dry run, reports only
 *   npx tsx scripts/link-employers-to-companies.ts --apply             # link perm + pwd
 *   npx tsx scripts/link-employers-to-companies.ts --apply --propagate-lca
 */

import { loadEnvConfig } from "@next/env"
loadEnvConfig(process.cwd())

import { getPostgresPool } from "@/lib/postgres/server"

const APPLY = process.argv.includes("--apply")
const PROPAGATE = process.argv.includes("--propagate-lca")

/**
 * Shortest normalized employer name we will link on. Between the 4 used for read-time signal
 * suppression and the 8 used for the high-stakes cap-exempt flag: a wrong link here shows one
 * employer's filings on another's page, which is misinformation but not a visa decision.
 */
const MIN_KEY_LENGTH = 6

/**
 * Deterministic preference among several companies sharing a normalized name. Ordered by how
 * strongly each signal indicates "this is the real, canonical record".
 */
const TIE_BREAK = `
  (c.duplicate_of_company_id IS NULL) DESC,
  (c.status = 'active') DESC,
  c.is_active DESC,
  COALESCE(c.job_count, 0) DESC,
  (c.domain NOT LIKE '%%-tenant' AND c.domain NOT LIKE '%%.discovered'
     AND c.domain NOT LIKE '%%-discovered' AND c.domain NOT LIKE '%%discovered') DESC,
  c.created_at ASC,
  c.id ASC`

function linkSql(table: "perm_records" | "pwd_records", dryRun: boolean): string {
  const cte = `
    WITH cand AS (
      SELECT t.case_number,
             c.id AS cid,
             row_number() OVER (PARTITION BY t.case_number ORDER BY ${TIE_BREAK}) AS rk
        FROM ${table} t
        JOIN companies c ON c.name_normalized = company_name_norm(t.employer_name)
       WHERE t.company_id IS NULL
         AND t.employer_name IS NOT NULL
         AND length(company_name_norm(t.employer_name)) >= ${MIN_KEY_LENGTH}
    )`
  if (dryRun) {
    return `${cte}
      SELECT count(*)::text AS rows_to_link, count(DISTINCT cid)::text AS companies
        FROM cand WHERE rk = 1`
  }
  return `${cte}
    UPDATE ${table} t SET company_id = cand.cid
      FROM cand WHERE cand.case_number = t.case_number AND cand.rk = 1`
}

async function main(): Promise<void> {
  const pool = getPostgresPool()
  const client = await pool.connect()

  try {
    await client.query("SET statement_timeout = 0")

    // ---- ambiguity report -------------------------------------------------
    const { rows: amb } = await client.query<{ employers: string; unambiguous: string; ambiguous: string }>(
      `WITH m AS (
         SELECT company_name_norm(p.employer_name) e, count(DISTINCT c.id) n
           FROM perm_records p JOIN companies c ON c.name_normalized = company_name_norm(p.employer_name)
          WHERE length(company_name_norm(p.employer_name)) >= $1
          GROUP BY 1)
       SELECT count(*)::text employers,
              count(*) FILTER (WHERE n = 1)::text unambiguous,
              count(*) FILTER (WHERE n > 1)::text ambiguous
         FROM m`,
      [MIN_KEY_LENGTH]
    )
    console.log(
      `PERM employer names matching a company: ${Number(amb[0].employers).toLocaleString()} ` +
        `(${Number(amb[0].unambiguous).toLocaleString()} unambiguous, ` +
        `${Number(amb[0].ambiguous).toLocaleString()} ambiguous → tie-broken)`
    )

    if (Number(amb[0].ambiguous) > 0) {
      const { rows: examples } = await client.query<{ e: string; chosen: string; others: string }>(
        `WITH pairs AS (
           SELECT DISTINCT company_name_norm(p.employer_name) e, c.id, c.name,
                  c.duplicate_of_company_id, c.status, c.is_active, c.job_count, c.domain, c.created_at
             FROM perm_records p JOIN companies c ON c.name_normalized = company_name_norm(p.employer_name)
            WHERE length(company_name_norm(p.employer_name)) >= $1
         ), ranked AS (
           SELECT e, name,
                  row_number() OVER (PARTITION BY e ORDER BY ${TIE_BREAK.replace(/c\./g, "")}) rk,
                  count(*) OVER (PARTITION BY e) n
             FROM pairs c
         )
         SELECT e, max(name) FILTER (WHERE rk = 1) AS chosen, max(n)::text AS others
           FROM ranked WHERE n > 1 GROUP BY e ORDER BY max(n) DESC LIMIT 5`,
        [MIN_KEY_LENGTH]
      )
      console.log("  tie-break examples (name → chosen company, of N candidates):")
      for (const r of examples) console.log(`    ${r.e} → ${r.chosen}  (of ${r.others})`)
    }

    // ---- phase 1: link perm + pwd ----------------------------------------
    for (const table of ["perm_records", "pwd_records"] as const) {
      if (!APPLY) {
        const { rows } = await client.query<{ rows_to_link: string; companies: string }>(linkSql(table, true))
        console.log(
          `\n[${table}] would link ${Number(rows[0].rows_to_link).toLocaleString()} rows ` +
            `to ${Number(rows[0].companies).toLocaleString()} companies`
        )
      } else {
        const res = await client.query(linkSql(table, false))
        console.log(`\n[${table}] linked ${(res.rowCount ?? 0).toLocaleString()} rows`)
      }
    }

    // ---- phase 2: repair LCA via FEIN ------------------------------------
    // Only FEINs resolving to exactly ONE company are used. A FEIN is a legal-entity identifier,
    // so a clean 1:1 here is far more trustworthy than any name comparison.
    const feinMapCte = `
      WITH fein_map AS (
        SELECT employer_fein, (array_agg(DISTINCT company_id))[1] AS cid
          FROM (
            SELECT employer_fein, company_id FROM perm_records
             WHERE employer_fein IS NOT NULL AND company_id IS NOT NULL
            UNION
            SELECT employer_fein, company_id FROM pwd_records
             WHERE employer_fein IS NOT NULL AND company_id IS NOT NULL
          ) u
         GROUP BY employer_fein
        HAVING count(DISTINCT company_id) = 1
      )`

    if (!PROPAGATE) {
      const { rows } = await client.query<{ feins: string; rows_affected: string }>(
        `${feinMapCte}
         SELECT (SELECT count(*)::text FROM fein_map) AS feins,
                count(*)::text AS rows_affected
           FROM lca_records l JOIN fein_map f ON f.employer_fein = l.employer_fein
          WHERE l.company_id IS NULL`
      )
      console.log(
        `\n[lca_records] ${Number(rows[0].feins).toLocaleString()} unambiguous FEINs would link ` +
          `${Number(rows[0].rows_affected).toLocaleString()} currently-unlinked rows ` +
          `(pass --propagate-lca to apply)`
      )
    } else if (APPLY) {
      const before = await client.query<{ linked: string; total: string }>(
        `SELECT count(company_id)::text linked, count(*)::text total FROM lca_records`
      )
      const res = await client.query(
        `${feinMapCte}
         UPDATE lca_records l SET company_id = f.cid
           FROM fein_map f
          WHERE f.employer_fein = l.employer_fein AND l.company_id IS NULL`
      )
      const after = await client.query<{ linked: string; total: string }>(
        `SELECT count(company_id)::text linked, count(*)::text total FROM lca_records`
      )
      const pct = (r: { linked: string; total: string }) =>
        `${((100 * Number(r.linked)) / Number(r.total)).toFixed(1)}%`
      console.log(
        `\n[lca_records] linked ${(res.rowCount ?? 0).toLocaleString()} rows — ` +
          `${pct(before.rows[0])} → ${pct(after.rows[0])}`
      )
    } else {
      console.log("\n--propagate-lca requires --apply; skipped.")
    }

    if (!APPLY) console.log("\nDry run — nothing written. Re-run with --apply.")
    else console.log("\nNext: npx tsx scripts/rebuild-h1b-aggregates.ts --execute (aggregates read company_id)")
  } finally {
    client.release()
    await pool.end()
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
})
