#!/usr/bin/env node
// Run: node scripts/seed-jobs.mjs
// Requires: NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env.local

import { createClient } from "@supabase/supabase-js"
import { readFileSync } from "fs"
import { fileURLToPath } from "url"
import { dirname, join } from "path"

const __dir = dirname(fileURLToPath(import.meta.url))

// Load env vars from .env.local
const envPath = join(__dir, "../.env.local")
const env = readFileSync(envPath, "utf8")
  .split("\n")
  .filter((l) => l && !l.startsWith("#"))
  .reduce((acc, l) => {
    const [k, ...v] = l.split("=")
    if (k) acc[k.trim()] = v.join("=").trim()
    return acc
  }, {})

const url = env["NEXT_PUBLIC_SUPABASE_URL"]
const key = env["SUPABASE_SERVICE_ROLE_KEY"]

if (!url || !key) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local")
  process.exit(1)
}

const supabase = createClient(url, key, {
  auth: { persistSession: false },
})

// Fetch all company IDs by domain
const { data: companies, error: cErr } = await supabase
  .from("companies")
  .select("id, domain, name")

if (cErr) {
  console.error("Failed to fetch companies:", cErr.message)
  process.exit(1)
}

const byDomain = Object.fromEntries(companies.map((c) => [c.domain, c.id]))

console.log(`Found ${companies.length} companies`)

// All jobs to seed
const jobs = [
  // ── Google ─────────────────────────────────────────────────────────────────
  {
    domain: "google.com",
    title: "Senior Software Engineer, Infrastructure",
    normalized_title: "Senior Software Engineer",
    department: "Engineering",
    location: "Mountain View, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 185000,
    salary_max: 280000,
    apply_url: "https://careers.google.com/jobs/1001",
    external_id: "goog-1001",
    sponsors_h1b: true,
    sponsorship_score: 92,
    skills: ["Go", "Kubernetes", "Distributed Systems", "gRPC", "C++"],
    first_detected_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    domain: "google.com",
    title: "Staff Machine Learning Engineer",
    normalized_title: "Staff ML Engineer",
    department: "Google DeepMind",
    location: "New York, NY",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "staff",
    salary_min: 230000,
    salary_max: 340000,
    apply_url: "https://careers.google.com/jobs/1002",
    external_id: "goog-1002",
    sponsors_h1b: true,
    sponsorship_score: 95,
    skills: ["Python", "PyTorch", "TensorFlow", "JAX", "Distributed Training"],
    description: "We are seeking talented engineers for large-scale ML systems. We are committed to sponsoring H-1B visas for qualified candidates.",
    first_detected_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    domain: "google.com",
    title: "Product Manager, Google Cloud",
    normalized_title: "Product Manager",
    department: "Google Cloud",
    location: "Sunnyvale, CA",
    is_remote: false,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 145000,
    salary_max: 215000,
    apply_url: "https://careers.google.com/jobs/1003",
    external_id: "goog-1003",
    sponsors_h1b: true,
    sponsorship_score: 88,
    skills: ["Product Strategy", "SQL", "APIs", "Cloud Computing", "Go-to-Market"],
    first_detected_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    domain: "google.com",
    title: "UX Research Intern (Summer 2025)",
    normalized_title: "UX Research Intern",
    department: "Design",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "internship",
    seniority_level: "intern",
    salary_min: 50,
    salary_max: 55,
    apply_url: "https://careers.google.com/jobs/1004",
    external_id: "goog-1004",
    sponsors_h1b: true,
    sponsorship_score: 80,
    skills: ["User Research", "Figma", "Surveys", "Usability Testing", "Statistics"],
    first_detected_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Meta ───────────────────────────────────────────────────────────────────
  {
    domain: "meta.com",
    title: "Software Engineer, Reality Labs",
    normalized_title: "Software Engineer",
    department: "Reality Labs",
    location: "Redmond, WA",
    is_remote: false,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 165000,
    salary_max: 240000,
    apply_url: "https://www.metacareers.com/jobs/2001",
    external_id: "meta-2001",
    sponsors_h1b: true,
    sponsorship_score: 91,
    skills: ["C++", "OpenGL", "Vulkan", "Computer Vision", "SLAM"],
    description: "Join the Reality Labs team building the future of AR/VR. Meta sponsors H-1B and immigration support for all qualifying roles.",
    first_detected_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
  },
  {
    domain: "meta.com",
    title: "Senior Data Scientist, Ads",
    normalized_title: "Senior Data Scientist",
    department: "Monetization",
    location: "Menlo Park, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 190000,
    salary_max: 285000,
    apply_url: "https://www.metacareers.com/jobs/2002",
    external_id: "meta-2002",
    sponsors_h1b: true,
    sponsorship_score: 93,
    skills: ["Python", "R", "Causal Inference", "SQL", "Spark", "Experimentation"],
    first_detected_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    domain: "meta.com",
    title: "Engineering Manager, Infrastructure",
    normalized_title: "Engineering Manager",
    department: "Infrastructure",
    location: "Seattle, WA",
    is_remote: true,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "director",
    salary_min: 240000,
    salary_max: 360000,
    apply_url: "https://www.metacareers.com/jobs/2003",
    external_id: "meta-2003",
    sponsors_h1b: true,
    sponsorship_score: 90,
    skills: ["Team Leadership", "Distributed Systems", "Systems Design", "Go", "Java"],
    first_detected_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Apple ──────────────────────────────────────────────────────────────────
  {
    domain: "apple.com",
    title: "iOS Software Engineer",
    normalized_title: "iOS Software Engineer",
    department: "Software Engineering",
    location: "Cupertino, CA",
    is_remote: false,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 155000,
    salary_max: 235000,
    apply_url: "https://jobs.apple.com/3001",
    external_id: "aapl-3001",
    sponsors_h1b: true,
    sponsorship_score: 88,
    skills: ["Swift", "Objective-C", "UIKit", "SwiftUI", "Core Data"],
    first_detected_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
  {
    domain: "apple.com",
    title: "Machine Learning Researcher, Siri",
    normalized_title: "ML Researcher",
    department: "Siri & Information Intelligence",
    location: "Cupertino, CA",
    is_remote: false,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 210000,
    salary_max: 310000,
    apply_url: "https://jobs.apple.com/3002",
    external_id: "aapl-3002",
    sponsors_h1b: true,
    sponsorship_score: 90,
    skills: ["Python", "PyTorch", "NLP", "Speech Recognition", "Transformer Models"],
    first_detected_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    domain: "apple.com",
    title: "Hardware Engineer, Apple Silicon",
    normalized_title: "Hardware Engineer",
    department: "Silicon Engineering",
    location: "Cupertino, CA",
    is_remote: false,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 200000,
    salary_max: 300000,
    apply_url: "https://jobs.apple.com/3003",
    external_id: "aapl-3003",
    sponsors_h1b: true,
    sponsorship_score: 92,
    skills: ["VLSI", "RTL Design", "Verilog", "SystemVerilog", "RISC-V"],
    first_detected_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Microsoft ──────────────────────────────────────────────────────────────
  {
    domain: "microsoft.com",
    title: "Principal Software Engineer, Azure",
    normalized_title: "Principal Software Engineer",
    department: "Azure Core",
    location: "Redmond, WA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "principal",
    salary_min: 220000,
    salary_max: 340000,
    apply_url: "https://jobs.careers.microsoft.com/4001",
    external_id: "msft-4001",
    sponsors_h1b: true,
    sponsorship_score: 94,
    skills: ["C#", "Azure", "Distributed Systems", "Kubernetes", "Go"],
    description: "Microsoft sponsors and supports H-1B visa petitions for qualified technical roles. Work authorization assistance provided.",
    first_detected_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    domain: "microsoft.com",
    title: "Software Engineer II, GitHub",
    normalized_title: "Software Engineer",
    department: "GitHub",
    location: "Remote",
    is_remote: true,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 140000,
    salary_max: 210000,
    apply_url: "https://jobs.careers.microsoft.com/4002",
    external_id: "msft-4002",
    sponsors_h1b: true,
    sponsorship_score: 91,
    skills: ["Ruby", "TypeScript", "React", "PostgreSQL", "GraphQL"],
    first_detected_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
  },
  {
    domain: "microsoft.com",
    title: "Senior Product Manager, Copilot",
    normalized_title: "Senior Product Manager",
    department: "M365 AI",
    location: "Redmond, WA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 165000,
    salary_max: 250000,
    apply_url: "https://jobs.careers.microsoft.com/4003",
    external_id: "msft-4003",
    sponsors_h1b: true,
    sponsorship_score: 89,
    skills: ["Product Management", "AI/ML", "Customer Research", "OKRs", "B2B SaaS"],
    first_detected_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    domain: "microsoft.com",
    title: "Data & Applied Scientist, Bing",
    normalized_title: "Data Scientist",
    department: "Bing",
    location: "Bellevue, WA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 145000,
    salary_max: 215000,
    apply_url: "https://jobs.careers.microsoft.com/4004",
    external_id: "msft-4004",
    sponsors_h1b: true,
    sponsorship_score: 90,
    skills: ["Python", "Machine Learning", "NLP", "Spark", "Azure ML"],
    first_detected_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Amazon ─────────────────────────────────────────────────────────────────
  {
    domain: "amazon.com",
    title: "SDE II, Amazon Web Services",
    normalized_title: "Software Engineer",
    department: "AWS Lambda",
    location: "Seattle, WA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 155000,
    salary_max: 230000,
    apply_url: "https://www.amazon.jobs/5001",
    external_id: "amzn-5001",
    sponsors_h1b: true,
    sponsorship_score: 93,
    skills: ["Java", "Rust", "AWS", "Distributed Systems", "Microservices"],
    description: "Amazon will sponsor visa and provide immigration support for all new and existing employees who require it.",
    first_detected_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    domain: "amazon.com",
    title: "Senior SDE, Alexa AI",
    normalized_title: "Senior Software Engineer",
    department: "Alexa",
    location: "Seattle, WA",
    is_remote: false,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 190000,
    salary_max: 280000,
    apply_url: "https://www.amazon.jobs/5002",
    external_id: "amzn-5002",
    sponsors_h1b: true,
    sponsorship_score: 95,
    skills: ["Python", "NLP", "Deep Learning", "AWS", "Java"],
    first_detected_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    domain: "amazon.com",
    title: "Principal Product Manager – Technical",
    normalized_title: "Principal Product Manager",
    department: "AWS",
    location: "New York, NY",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "principal",
    salary_min: 200000,
    salary_max: 310000,
    apply_url: "https://www.amazon.jobs/5003",
    external_id: "amzn-5003",
    sponsors_h1b: true,
    sponsorship_score: 91,
    skills: ["Product Strategy", "APIs", "Cloud Computing", "SQL", "Technical Writing"],
    first_detected_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    domain: "amazon.com",
    title: "Software Development Engineer Intern",
    normalized_title: "SDE Intern",
    department: "Amazon",
    location: "Austin, TX",
    is_remote: false,
    is_hybrid: true,
    employment_type: "internship",
    seniority_level: "intern",
    salary_min: 48,
    salary_max: 52,
    apply_url: "https://www.amazon.jobs/5004",
    external_id: "amzn-5004",
    sponsors_h1b: true,
    sponsorship_score: 85,
    skills: ["Java", "Python", "Data Structures", "Algorithms", "AWS"],
    first_detected_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Stripe ─────────────────────────────────────────────────────────────────
  {
    domain: "stripe.com",
    title: "Software Engineer, Payments Infrastructure",
    normalized_title: "Software Engineer",
    department: "Payments",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 175000,
    salary_max: 255000,
    apply_url: "https://stripe.com/jobs/6001",
    external_id: "stripe-6001",
    sponsors_h1b: true,
    sponsorship_score: 85,
    skills: ["Ruby", "Go", "PostgreSQL", "Kafka", "Redis"],
    description: "Stripe provides immigration support including H-1B sponsorship for qualified engineers joining our team.",
    first_detected_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    domain: "stripe.com",
    title: "Senior Software Engineer, Developer Experience",
    normalized_title: "Senior Software Engineer",
    department: "Developer Platform",
    location: "Remote",
    is_remote: true,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 195000,
    salary_max: 275000,
    apply_url: "https://stripe.com/jobs/6002",
    external_id: "stripe-6002",
    sponsors_h1b: true,
    sponsorship_score: 82,
    skills: ["TypeScript", "Node.js", "APIs", "SDKs", "Documentation"],
    first_detected_at: new Date(Date.now() - 7 * 3600 * 1000).toISOString(),
  },
  {
    domain: "stripe.com",
    title: "Data Scientist, Risk",
    normalized_title: "Data Scientist",
    department: "Risk & Fraud",
    location: "Chicago, IL",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 145000,
    salary_max: 210000,
    apply_url: "https://stripe.com/jobs/6003",
    external_id: "stripe-6003",
    sponsors_h1b: true,
    sponsorship_score: 80,
    skills: ["Python", "SQL", "Scikit-learn", "Fraud Detection", "Statistical Modeling"],
    first_detected_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Linear ─────────────────────────────────────────────────────────────────
  {
    domain: "linear.app",
    title: "Software Engineer",
    normalized_title: "Software Engineer",
    department: "Engineering",
    location: "Remote",
    is_remote: true,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 140000,
    salary_max: 200000,
    apply_url: "https://linear.app/careers/7001",
    external_id: "linear-7001",
    sponsors_h1b: false,
    sponsorship_score: 35,
    skills: ["TypeScript", "React", "GraphQL", "PostgreSQL", "Electron"],
    description: "Applicants must be authorized to work in the US. We are not able to sponsor work visas at this time.",
    requires_authorization: true,
    first_detected_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    domain: "linear.app",
    title: "Product Designer",
    normalized_title: "Product Designer",
    department: "Design",
    location: "Remote",
    is_remote: true,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 135000,
    salary_max: 190000,
    apply_url: "https://linear.app/careers/7002",
    external_id: "linear-7002",
    sponsors_h1b: false,
    sponsorship_score: 38,
    skills: ["Figma", "Design Systems", "Motion Design", "User Research", "Prototyping"],
    first_detected_at: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Vercel ─────────────────────────────────────────────────────────────────
  {
    domain: "vercel.com",
    title: "Senior Software Engineer, Runtime",
    normalized_title: "Senior Software Engineer",
    department: "Engineering",
    location: "Remote",
    is_remote: true,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 170000,
    salary_max: 240000,
    apply_url: "https://vercel.com/careers/8001",
    external_id: "vercel-8001",
    sponsors_h1b: true,
    sponsorship_score: 70,
    skills: ["Rust", "Node.js", "Edge Computing", "WebAssembly", "TypeScript"],
    description: "Vercel can sponsor H-1B visas for exceptional candidates depending on experience and role requirements.",
    first_detected_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    domain: "vercel.com",
    title: "Developer Relations Engineer",
    normalized_title: "Developer Relations Engineer",
    department: "DevRel",
    location: "Remote",
    is_remote: true,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 130000,
    salary_max: 180000,
    apply_url: "https://vercel.com/careers/8002",
    external_id: "vercel-8002",
    sponsors_h1b: true,
    sponsorship_score: 68,
    skills: ["Next.js", "TypeScript", "Technical Writing", "Public Speaking", "React"],
    first_detected_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Notion ─────────────────────────────────────────────────────────────────
  {
    domain: "notion.so",
    title: "Full Stack Engineer, Editor",
    normalized_title: "Full Stack Engineer",
    department: "Engineering",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 155000,
    salary_max: 230000,
    apply_url: "https://www.notion.so/careers/9001",
    external_id: "notion-9001",
    sponsors_h1b: true,
    sponsorship_score: 75,
    skills: ["TypeScript", "React", "PostgreSQL", "Node.js", "CRDTs"],
    description: "Notion provides H-1B sponsorship and full immigration support as part of our commitment to global talent.",
    first_detected_at: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
  },
  {
    domain: "notion.so",
    title: "Product Manager, Enterprise",
    normalized_title: "Product Manager",
    department: "Product",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 155000,
    salary_max: 225000,
    apply_url: "https://www.notion.so/careers/9002",
    external_id: "notion-9002",
    sponsors_h1b: true,
    sponsorship_score: 72,
    skills: ["B2B SaaS", "Enterprise Sales", "Product Analytics", "Roadmapping", "SQL"],
    first_detected_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Figma ──────────────────────────────────────────────────────────────────
  {
    domain: "figma.com",
    title: "Software Engineer, Rendering",
    normalized_title: "Software Engineer",
    department: "Engineering",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 185000,
    salary_max: 265000,
    apply_url: "https://www.figma.com/careers/10001",
    external_id: "figma-10001",
    sponsors_h1b: true,
    sponsorship_score: 80,
    skills: ["C++", "WebGL", "WASM", "TypeScript", "Graphics Programming"],
    description: "Figma will consider H-1B sponsorship for roles requiring specialized expertise in graphics and rendering engineering.",
    first_detected_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    domain: "figma.com",
    title: "Staff Designer, Design Systems",
    normalized_title: "Staff Designer",
    department: "Design",
    location: "New York, NY",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "staff",
    salary_min: 195000,
    salary_max: 280000,
    apply_url: "https://www.figma.com/careers/10002",
    external_id: "figma-10002",
    sponsors_h1b: true,
    sponsorship_score: 78,
    skills: ["Design Systems", "Figma", "Component Libraries", "Documentation", "Accessibility"],
    first_detected_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    domain: "figma.com",
    title: "Machine Learning Engineer, AI Features",
    normalized_title: "ML Engineer",
    department: "AI",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 165000,
    salary_max: 240000,
    apply_url: "https://www.figma.com/careers/10003",
    external_id: "figma-10003",
    sponsors_h1b: true,
    sponsorship_score: 82,
    skills: ["Python", "PyTorch", "Computer Vision", "LLMs", "TypeScript"],
    first_detected_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },

  // ── Anthropic ──────────────────────────────────────────────────────────────
  {
    domain: "anthropic.com",
    title: "Research Engineer, Alignment",
    normalized_title: "Research Engineer",
    department: "Alignment Science",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 200000,
    salary_max: 340000,
    apply_url: "https://www.anthropic.com/careers/11001",
    external_id: "anth-11001",
    sponsors_h1b: true,
    sponsorship_score: 83,
    skills: ["Python", "PyTorch", "Reinforcement Learning", "LLMs", "Interpretability"],
    description: "We provide full immigration support including H-1B sponsorship for research roles. Authorization to work in the US required at hire.",
    first_detected_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
  },
  {
    domain: "anthropic.com",
    title: "Software Engineer, Claude.ai",
    normalized_title: "Software Engineer",
    department: "Product Engineering",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 175000,
    salary_max: 260000,
    apply_url: "https://www.anthropic.com/careers/11002",
    external_id: "anth-11002",
    sponsors_h1b: true,
    sponsorship_score: 85,
    skills: ["TypeScript", "React", "Python", "APIs", "PostgreSQL"],
    first_detected_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
  {
    domain: "anthropic.com",
    title: "Senior Research Scientist, Safety",
    normalized_title: "Research Scientist",
    department: "Safety Research",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 230000,
    salary_max: 380000,
    apply_url: "https://www.anthropic.com/careers/11003",
    external_id: "anth-11003",
    sponsors_h1b: true,
    sponsorship_score: 88,
    skills: ["Python", "Deep Learning", "NLP", "Research Methods", "Statistics"],
    first_detected_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },

  // ── OpenAI ─────────────────────────────────────────────────────────────────
  {
    domain: "openai.com",
    title: "Research Scientist, Pretraining",
    normalized_title: "Research Scientist",
    department: "Research",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 250000,
    salary_max: 400000,
    apply_url: "https://openai.com/careers/12001",
    external_id: "oai-12001",
    sponsors_h1b: true,
    sponsorship_score: 85,
    skills: ["Python", "PyTorch", "Distributed Training", "LLMs", "CUDA"],
    description: "OpenAI sponsors H-1B and O-1 visas for researchers and engineers. Immigration assistance provided from day one.",
    first_detected_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    domain: "openai.com",
    title: "Software Engineer, API Platform",
    normalized_title: "Software Engineer",
    department: "Platform",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 180000,
    salary_max: 270000,
    apply_url: "https://openai.com/careers/12002",
    external_id: "oai-12002",
    sponsors_h1b: true,
    sponsorship_score: 87,
    skills: ["Python", "Go", "Kubernetes", "Postgres", "gRPC"],
    first_detected_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    domain: "openai.com",
    title: "Product Manager, ChatGPT",
    normalized_title: "Product Manager",
    department: "ChatGPT",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 175000,
    salary_max: 260000,
    apply_url: "https://openai.com/careers/12003",
    external_id: "oai-12003",
    sponsors_h1b: true,
    sponsorship_score: 83,
    skills: ["Consumer Product", "AI/ML", "Growth", "Analytics", "User Research"],
    first_detected_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },

  // ── JPMorgan Chase ─────────────────────────────────────────────────────────
  {
    domain: "jpmorganchase.com",
    title: "Software Engineer III, Payments Tech",
    normalized_title: "Software Engineer",
    department: "Technology",
    location: "Jersey City, NJ",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 130000,
    salary_max: 195000,
    apply_url: "https://careers.jpmorgan.com/13001",
    external_id: "jpm-13001",
    sponsors_h1b: true,
    sponsorship_score: 88,
    skills: ["Java", "Spring Boot", "Kafka", "Oracle", "Microservices"],
    description: "JPMorgan Chase & Co. will consider candidates requiring H-1B sponsorship for this position.",
    first_detected_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
  },
  {
    domain: "jpmorganchase.com",
    title: "Quantitative Researcher",
    normalized_title: "Quantitative Researcher",
    department: "CIB Quant Research",
    location: "New York, NY",
    is_remote: false,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 175000,
    salary_max: 280000,
    apply_url: "https://careers.jpmorgan.com/13002",
    external_id: "jpm-13002",
    sponsors_h1b: true,
    sponsorship_score: 92,
    skills: ["Python", "C++", "Statistics", "Financial Modeling", "Stochastic Calculus"],
    first_detected_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    domain: "jpmorganchase.com",
    title: "Data Engineer, Risk Tech",
    normalized_title: "Data Engineer",
    department: "Risk Technology",
    location: "Columbus, OH",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 105000,
    salary_max: 160000,
    apply_url: "https://careers.jpmorgan.com/13003",
    external_id: "jpm-13003",
    sponsors_h1b: true,
    sponsorship_score: 85,
    skills: ["Python", "Spark", "Hadoop", "SQL", "Airflow"],
    first_detected_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Goldman Sachs ──────────────────────────────────────────────────────────
  {
    domain: "goldmansachs.com",
    title: "Software Engineer, Strats & Engineering",
    normalized_title: "Software Engineer",
    department: "Engineering",
    location: "New York, NY",
    is_remote: false,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 145000,
    salary_max: 220000,
    apply_url: "https://www.goldmansachs.com/careers/14001",
    external_id: "gs-14001",
    sponsors_h1b: true,
    sponsorship_score: 86,
    skills: ["Java", "Python", "Slang", "Market Data", "Distributed Systems"],
    description: "Goldman Sachs sponsors H-1B visas. Must be authorized to work in the US or have an active visa petition.",
    first_detected_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    domain: "goldmansachs.com",
    title: "Machine Learning Engineer, Risk",
    normalized_title: "ML Engineer",
    department: "Risk Engineering",
    location: "New York, NY",
    is_remote: false,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 185000,
    salary_max: 270000,
    apply_url: "https://www.goldmansachs.com/careers/14002",
    external_id: "gs-14002",
    sponsors_h1b: true,
    sponsorship_score: 90,
    skills: ["Python", "TensorFlow", "Spark", "Time Series", "Risk Modeling"],
    first_detected_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },

  // ── CVS Health ─────────────────────────────────────────────────────────────
  {
    domain: "cvshealth.com",
    title: "Senior Software Engineer, Digital Health",
    normalized_title: "Senior Software Engineer",
    department: "Digital Technology",
    location: "Woonsocket, RI",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 120000,
    salary_max: 175000,
    apply_url: "https://jobs.cvshealth.com/15001",
    external_id: "cvs-15001",
    sponsors_h1b: true,
    sponsorship_score: 73,
    skills: ["Java", "Spring", "React", "AWS", "FHIR"],
    description: "CVS Health will sponsor H-1B work authorization for qualified candidates with specialized skills.",
    first_detected_at: new Date(Date.now() - 9 * 3600 * 1000).toISOString(),
  },
  {
    domain: "cvshealth.com",
    title: "Data Analyst, Pharmacy Analytics",
    normalized_title: "Data Analyst",
    department: "Analytics",
    location: "Remote",
    is_remote: true,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 75000,
    salary_max: 110000,
    apply_url: "https://jobs.cvshealth.com/15002",
    external_id: "cvs-15002",
    sponsors_h1b: false,
    sponsorship_score: 55,
    skills: ["SQL", "Tableau", "Python", "Healthcare Data", "Excel"],
    first_detected_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },

  // ── UnitedHealth ──────────────────────────────────────────────────────────
  {
    domain: "unitedhealthgroup.com",
    title: "Software Engineer, Optum Digital",
    normalized_title: "Software Engineer",
    department: "Optum Technology",
    location: "Eden Prairie, MN",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 110000,
    salary_max: 165000,
    apply_url: "https://careers.unitedhealthgroup.com/16001",
    external_id: "uhg-16001",
    sponsors_h1b: true,
    sponsorship_score: 78,
    skills: ["Java", "Microservices", "AWS", "React", "HL7"],
    description: "UnitedHealth Group is committed to workforce diversity and provides H-1B visa sponsorship for qualified technical candidates.",
    first_detected_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
  {
    domain: "unitedhealthgroup.com",
    title: "Machine Learning Engineer, Claims AI",
    normalized_title: "ML Engineer",
    department: "AI & Data Science",
    location: "Remote",
    is_remote: true,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 145000,
    salary_max: 210000,
    apply_url: "https://careers.unitedhealthgroup.com/16002",
    external_id: "uhg-16002",
    sponsors_h1b: true,
    sponsorship_score: 80,
    skills: ["Python", "TensorFlow", "NLP", "Healthcare AI", "Apache Kafka"],
    first_detected_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Nike ───────────────────────────────────────────────────────────────────
  {
    domain: "nike.com",
    title: "Senior Software Engineer, Digital Commerce",
    normalized_title: "Senior Software Engineer",
    department: "Nike Digital",
    location: "Beaverton, OR",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 135000,
    salary_max: 195000,
    apply_url: "https://jobs.nike.com/17001",
    external_id: "nike-17001",
    sponsors_h1b: true,
    sponsorship_score: 71,
    skills: ["Node.js", "React", "GraphQL", "AWS", "TypeScript"],
    description: "Nike may provide H-1B sponsorship for uniquely qualified candidates on a case-by-case basis.",
    first_detected_at: new Date(Date.now() - 11 * 3600 * 1000).toISOString(),
  },
  {
    domain: "nike.com",
    title: "Data Scientist, Consumer Analytics",
    normalized_title: "Data Scientist",
    department: "Consumer Analytics",
    location: "Portland, OR",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 110000,
    salary_max: 160000,
    apply_url: "https://jobs.nike.com/17002",
    external_id: "nike-17002",
    sponsors_h1b: true,
    sponsorship_score: 68,
    skills: ["Python", "R", "SQL", "A/B Testing", "Retail Analytics"],
    first_detected_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Airbnb ─────────────────────────────────────────────────────────────────
  {
    domain: "airbnb.com",
    title: "Software Engineer, Trust & Safety",
    normalized_title: "Software Engineer",
    department: "Trust",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 160000,
    salary_max: 235000,
    apply_url: "https://careers.airbnb.com/18001",
    external_id: "airbnb-18001",
    sponsors_h1b: true,
    sponsorship_score: 81,
    skills: ["Python", "Java", "Machine Learning", "Fraud Detection", "Kafka"],
    description: "Airbnb sponsors H-1B visas and provides comprehensive immigration support for all qualifying employees globally.",
    first_detected_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    domain: "airbnb.com",
    title: "Senior Product Designer",
    normalized_title: "Senior Product Designer",
    department: "Design",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 155000,
    salary_max: 225000,
    apply_url: "https://careers.airbnb.com/18002",
    external_id: "airbnb-18002",
    sponsors_h1b: true,
    sponsorship_score: 79,
    skills: ["Figma", "Product Design", "Design Systems", "User Research", "Prototyping"],
    first_detected_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
  },
  {
    domain: "airbnb.com",
    title: "ML Engineer, Search & Discovery",
    normalized_title: "ML Engineer",
    department: "Search",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 185000,
    salary_max: 265000,
    apply_url: "https://careers.airbnb.com/18003",
    external_id: "airbnb-18003",
    sponsors_h1b: true,
    sponsorship_score: 85,
    skills: ["Python", "PyTorch", "Search Ranking", "NLP", "Spark"],
    first_detected_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Cloudflare ─────────────────────────────────────────────────────────────
  {
    domain: "cloudflare.com",
    title: "Software Engineer, Edge Network",
    normalized_title: "Software Engineer",
    department: "Engineering",
    location: "Austin, TX",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "mid",
    salary_min: 150000,
    salary_max: 215000,
    apply_url: "https://www.cloudflare.com/careers/19001",
    external_id: "cf-19001",
    sponsors_h1b: true,
    sponsorship_score: 78,
    skills: ["Rust", "Go", "Networking", "Linux", "Distributed Systems"],
    description: "Cloudflare will sponsor visas for roles where we cannot find qualified local candidates. H-1B sponsorship available.",
    first_detected_at: new Date(Date.now() - 7 * 3600 * 1000).toISOString(),
  },
  {
    domain: "cloudflare.com",
    title: "Senior Reliability Engineer",
    normalized_title: "Senior SRE",
    department: "Infrastructure",
    location: "Remote",
    is_remote: true,
    is_hybrid: false,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 165000,
    salary_max: 235000,
    apply_url: "https://www.cloudflare.com/careers/19002",
    external_id: "cf-19002",
    sponsors_h1b: true,
    sponsorship_score: 76,
    skills: ["SRE", "Kubernetes", "Prometheus", "Go", "Incident Response"],
    first_detected_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    domain: "cloudflare.com",
    title: "Security Research Engineer",
    normalized_title: "Security Engineer",
    department: "Security Research",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 175000,
    salary_max: 250000,
    apply_url: "https://www.cloudflare.com/careers/19003",
    external_id: "cf-19003",
    sponsors_h1b: true,
    sponsorship_score: 80,
    skills: ["Security Research", "Reverse Engineering", "Cryptography", "Python", "C"],
    first_detected_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },

  // ── Databricks ─────────────────────────────────────────────────────────────
  {
    domain: "databricks.com",
    title: "Senior Software Engineer, Spark Core",
    normalized_title: "Senior Software Engineer",
    department: "Engineering",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 195000,
    salary_max: 285000,
    apply_url: "https://www.databricks.com/company/careers/20001",
    external_id: "db-20001",
    sponsors_h1b: true,
    sponsorship_score: 84,
    skills: ["Scala", "Java", "Apache Spark", "Distributed Computing", "SQL"],
    description: "Databricks actively supports H-1B sponsorship and immigration assistance for all qualifying technical employees.",
    first_detected_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    domain: "databricks.com",
    title: "Staff ML Engineer, Data Intelligence",
    normalized_title: "Staff ML Engineer",
    department: "AI Research",
    location: "Seattle, WA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "staff",
    salary_min: 225000,
    salary_max: 330000,
    apply_url: "https://www.databricks.com/company/careers/20002",
    external_id: "db-20002",
    sponsors_h1b: true,
    sponsorship_score: 88,
    skills: ["Python", "PyTorch", "LLMs", "Spark", "MLflow"],
    first_detected_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
  {
    domain: "databricks.com",
    title: "Product Manager, Lakehouse",
    normalized_title: "Product Manager",
    department: "Product",
    location: "San Francisco, CA",
    is_remote: false,
    is_hybrid: true,
    employment_type: "fulltime",
    seniority_level: "senior",
    salary_min: 165000,
    salary_max: 240000,
    apply_url: "https://www.databricks.com/company/careers/20003",
    external_id: "db-20003",
    sponsors_h1b: true,
    sponsorship_score: 82,
    skills: ["Data Engineering", "Cloud Platforms", "SQL", "APIs", "Product Analytics"],
    first_detected_at: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },
]

// Insert jobs in batches
let inserted = 0
let skipped = 0

for (const job of jobs) {
  const companyId = byDomain[job.domain]
  if (!companyId) {
    console.warn(`  ⚠ No company found for domain: ${job.domain}`)
    skipped++
    continue
  }

  const { domain, ...jobData } = job
  const row = {
    ...jobData,
    company_id: companyId,
    last_seen_at: new Date().toISOString(),
    is_active: true,
  }

  const { error } = await supabase.from("jobs").insert(row)
  if (error) {
    console.error(`  ✗ Failed to insert ${job.title} (${job.domain}):`, error.message)
  } else {
    inserted++
    process.stdout.write(`  ✓ ${job.title} @ ${job.domain}\n`)
  }
}

// Update job_count on all companies
console.log("\nUpdating job_count on companies…")
for (const company of companies) {
  const { count } = await supabase
    .from("jobs")
    .select("*", { count: "exact", head: true })
    .eq("company_id", company.id)
    .eq("is_active", true)

  await supabase
    .from("companies")
    .update({ job_count: count ?? 0 })
    .eq("id", company.id)
}

console.log(`\nDone! Inserted ${inserted} jobs, skipped ${skipped}.`)
