/**
 * Seed ban-the-box and background check protection data for all 50 states + DC.
 *
 * Usage:
 *   npx tsx scripts/seed-state-protections.ts
 *   npx tsx scripts/seed-state-protections.ts --dry-run
 */

import { loadEnvConfig } from "@next/env"
import { Pool } from "pg"

loadEnvConfig(process.cwd())

const dryRun = process.argv.includes("--dry-run")

type StateRow = {
  state_code: string
  state_name: string
  has_ban_the_box: boolean
  ban_the_box_scope: "all_employers" | "large_employers" | "public_only" | "none"
  ban_the_box_law_name: string | null
  lookback_limit_years: number | null
  lookback_limit_notes: string | null
  requires_individual_assessment: boolean
  allows_expungement_nondisclosure: boolean
  expungement_notes: string | null
  credit_check_restricted: boolean
  credit_check_notes: string | null
  last_updated: string
}

const STATES: StateRow[] = [
  // ── States with strong ban-the-box ──────────────────────────────────────────
  {
    state_code: "CA",
    state_name: "California",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "AB 1008 / Fair Chance Act",
    lookback_limit_years: 7,
    lookback_limit_notes: "7-year lookback for most convictions under ICRAA. Arrests not resulting in conviction cannot be reported after 7 years.",
    requires_individual_assessment: true,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Prop 47 reduced many felonies to misdemeanors. AB 1076 (2023) provides automatic expungement for eligible records. Employers may not consider expunged records.",
    credit_check_restricted: true,
    credit_check_notes: "ICRAA restricts credit checks to roles where credit history is substantially job-related.",
    last_updated: "2024-01-01",
  },
  {
    state_code: "NY",
    state_name: "New York",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Article 23-A / Correction Law",
    lookback_limit_years: null,
    lookback_limit_notes: "No statutory lookback limit but individualized assessment is mandatory. NYC adds additional protections under the Fair Chance Act.",
    requires_individual_assessment: true,
    allows_expungement_nondisclosure: true,
    expungement_notes: "NY allows sealing of up to 2 convictions (max 1 felony) after 10 years. Sealed records need not be disclosed.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "IL",
    state_name: "Illinois",
    has_ban_the_box: true,
    ban_the_box_scope: "large_employers",
    ban_the_box_law_name: "Job Opportunities for Qualified Applicants Act (JCAR)",
    lookback_limit_years: 7,
    lookback_limit_notes: "7-year lookback for positions paying under $75,000/year. No limit for positions over $75k.",
    requires_individual_assessment: true,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Illinois allows expungement for many offenses. The Cannabis Regulation Act allows automatic expungement of cannabis-related convictions.",
    credit_check_restricted: true,
    credit_check_notes: "Employee Credit Privacy Act restricts credit checks to roles where credit is directly related to the position.",
    last_updated: "2024-01-01",
  },
  {
    state_code: "WA",
    state_name: "Washington",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Washington Fair Chance Act",
    lookback_limit_years: 10,
    lookback_limit_notes: "10-year lookback for most roles. Employers may not consider arrests not resulting in conviction.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Washington allows vacation of certain convictions. Vacated convictions need not be disclosed.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "CO",
    state_name: "Colorado",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Colorado Chance to Compete Act",
    lookback_limit_years: null,
    lookback_limit_notes: "No statutory lookback limit but criminal history inquiry is deferred until conditional offer stage.",
    requires_individual_assessment: true,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Colorado allows sealing of many criminal records. Sealed records need not be disclosed to employers.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "MA",
    state_name: "Massachusetts",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "CORI Reform / An Act Relative to Criminal Records",
    lookback_limit_years: 7,
    lookback_limit_notes: "3-year lookback for misdemeanors, 7-year lookback for felonies. Certain serious offenses are permanently reportable.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Massachusetts allows sealing (3 years for misdemeanors, 7 for felonies) and expungement for first-time offenders under 21.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "NJ",
    state_name: "New Jersey",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Opportunity to Compete Act",
    lookback_limit_years: 6,
    lookback_limit_notes: "6-year lookback. Criminal history inquiry deferred until after first interview.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "New Jersey has broad expungement eligibility after 5 years for most offenses. Clean Slate law allows automatic expungement after 10 years.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "MD",
    state_name: "Maryland",
    has_ban_the_box: true,
    ban_the_box_scope: "large_employers",
    ban_the_box_law_name: "Maryland Criminal Record Screening Act",
    lookback_limit_years: null,
    lookback_limit_notes: "Applies to employers with 15+ employees. Criminal history inquiry deferred to conditional offer stage.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Maryland allows expungement for acquittals, dismissed charges, and some convictions after waiting periods.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "MN",
    state_name: "Minnesota",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Minnesota Human Rights Act amendment",
    lookback_limit_years: null,
    lookback_limit_notes: "Criminal history inquiry deferred until applicant has been selected for interview or received conditional offer.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Minnesota allows expungement for many offenses including petty misdemeanors and some felonies.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "CT",
    state_name: "Connecticut",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "An Act Concerning Fair Chance Employment",
    lookback_limit_years: null,
    lookback_limit_notes: "Criminal history inquiry deferred until after first interview for private employers (5+ employees).",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Connecticut allows erasure of criminal records for certain offenses after waiting periods.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "OR",
    state_name: "Oregon",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Oregon Fair Chance Act",
    lookback_limit_years: null,
    lookback_limit_notes: "Criminal history inquiry deferred until conditional offer stage for employers with 6+ employees.",
    requires_individual_assessment: true,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Oregon allows expungement of certain convictions after 3 years for Class C felonies and 1 year for misdemeanors.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "HI",
    state_name: "Hawaii",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Hawaii Pre-Employment Inquiries Law",
    lookback_limit_years: 10,
    lookback_limit_notes: "10-year lookback. Employers cannot inquire about convictions that occurred more than 10 years ago.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: false,
    expungement_notes: null,
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "RI",
    state_name: "Rhode Island",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Rhode Island Fair Employment Practices Act",
    lookback_limit_years: null,
    lookback_limit_notes: "Criminal history inquiry deferred until after first interview.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Rhode Island allows expungement for first-time offenders after 5 years.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "DC",
    state_name: "Washington D.C.",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Fair Criminal Record Screening Amendment Act",
    lookback_limit_years: null,
    lookback_limit_notes: "Criminal history inquiry deferred until conditional offer stage. Applies to employers with 11+ employees.",
    requires_individual_assessment: true,
    allows_expungement_nondisclosure: true,
    expungement_notes: "DC allows sealing of arrests and some convictions. Sealed records need not be disclosed.",
    credit_check_restricted: true,
    credit_check_notes: "DC Employment Credit Check Amendment Act restricts credit checks to jobs where credit is substantially related.",
    last_updated: "2024-01-01",
  },
  {
    state_code: "VT",
    state_name: "Vermont",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Vermont Fair Employment Practices Act",
    lookback_limit_years: null,
    lookback_limit_notes: "Criminal history inquiry deferred until after first interview.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Vermont allows expungement of many offenses.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "NM",
    state_name: "New Mexico",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "New Mexico Caregiver Criminal History Screening Reform",
    lookback_limit_years: null,
    lookback_limit_notes: "Criminal history inquiry deferred to conditional offer stage.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "New Mexico allows expungement after waiting periods depending on offense level.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "LA",
    state_name: "Louisiana",
    has_ban_the_box: true,
    ban_the_box_scope: "public_only",
    ban_the_box_law_name: "Louisiana RS 23:291.1",
    lookback_limit_years: null,
    lookback_limit_notes: "Applies to state government employers only. Private employers have no statutory ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Louisiana allows expungement for first-time felony convictions after 5 years and misdemeanors after 5 years.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "KY",
    state_name: "Kentucky",
    has_ban_the_box: true,
    ban_the_box_scope: "public_only",
    ban_the_box_law_name: "Kentucky Executive Order",
    lookback_limit_years: null,
    lookback_limit_notes: "State government employers only. No private employer ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Kentucky allows expungement of Class D felonies and misdemeanors after 5 years.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "NV",
    state_name: "Nevada",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Nevada SB 353",
    lookback_limit_years: 7,
    lookback_limit_notes: "7-year lookback applies for most roles.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Nevada allows sealing of criminal records after waiting periods (2–15 years depending on offense).",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "MI",
    state_name: "Michigan",
    has_ban_the_box: true,
    ban_the_box_scope: "public_only",
    ban_the_box_law_name: "Michigan Executive Directive 2020-3",
    lookback_limit_years: null,
    lookback_limit_notes: "State government employers only per Executive Directive. No private employer ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Michigan's Clean Slate law (2021) allows expungement of up to 3 felonies and unlimited misdemeanors after 7 years.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  // ── States with no ban-the-box or public-only ──────────────────────────────
  {
    state_code: "TX",
    state_name: "Texas",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No lookback limit. Private employers may inquire about criminal history at any point in hiring.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Texas allows expungement (expunction) for arrests that did not lead to conviction and some deferred adjudications. Orders of Nondisclosure seal records from most employers.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "FL",
    state_name: "Florida",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No lookback limit. No statewide ban-the-box law for private employers.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Florida allows sealing and expungement for first-time offenders who did not plead guilty. Limited eligibility.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "GA",
    state_name: "Georgia",
    has_ban_the_box: true,
    ban_the_box_scope: "public_only",
    ban_the_box_law_name: "Georgia SB 365",
    lookback_limit_years: null,
    lookback_limit_notes: "State agencies only. Private employers have no restriction on when to ask about criminal history.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Georgia allows record restriction (not full expungement) for arrests without conviction and some first-offender cases.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "PA",
    state_name: "Pennsylvania",
    has_ban_the_box: true,
    ban_the_box_scope: "public_only",
    ban_the_box_law_name: "Pennsylvania Clean Slate / Criminal History Record Information Act",
    lookback_limit_years: null,
    lookback_limit_notes: "State government employers only. Philadelphia has broader protections at city level.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Pennsylvania Clean Slate Act (2018) allows automatic sealing of non-violent misdemeanors after 10 years. Full expungement available for summary offenses.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "OH",
    state_name: "Ohio",
    has_ban_the_box: true,
    ban_the_box_scope: "public_only",
    ban_the_box_law_name: "Ohio Executive Order",
    lookback_limit_years: null,
    lookback_limit_notes: "State government employers only.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Ohio allows sealing of most first-time convictions after 1–3 years. Expanded eligibility under SB 288.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "AZ",
    state_name: "Arizona",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide law. Phoenix and Tucson have local ordinances.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Arizona set-aside law allows courts to set aside convictions. Not a full expungement but reduces barriers.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "IN",
    state_name: "Indiana",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No ban-the-box law for private employers.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Indiana allows restricted access to records (similar to expungement) for many offenses after 5–10 years.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "MO",
    state_name: "Missouri",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide law. Kansas City and St. Louis have local ordinances.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Missouri allows expungement after 3 years for misdemeanors and 7 years for non-violent felonies.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "TN",
    state_name: "Tennessee",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No ban-the-box for private employers.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Tennessee allows expungement for certain misdemeanors and felony arrests that did not result in conviction.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "NC",
    state_name: "North Carolina",
    has_ban_the_box: true,
    ban_the_box_scope: "public_only",
    ban_the_box_law_name: "North Carolina HB 809",
    lookback_limit_years: null,
    lookback_limit_notes: "State and local government employers only.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "North Carolina allows expungement for first-time offenders and certain non-violent offenses after waiting periods.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "SC",
    state_name: "South Carolina",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban-the-box law.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "South Carolina allows expungement for certain first-time offenses after waiting periods.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "VA",
    state_name: "Virginia",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Virginia SB 1280 / Fair Chance Hiring",
    lookback_limit_years: null,
    lookback_limit_notes: "Criminal history inquiry deferred until after first interview for employers with 5+ employees.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Virginia allows expungement for arrests not resulting in conviction and absolute pardons. Limited conviction expungement.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "WI",
    state_name: "Wisconsin",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban. Madison and Milwaukee have local ordinances.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Wisconsin allows expungement for offenders who were under 25 at the time of the offense and sentenced to 6 years or less.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "IA",
    state_name: "Iowa",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban. No lookback limit.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: false,
    expungement_notes: null,
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "KS",
    state_name: "Kansas",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Kansas allows expungement for many offenses after waiting periods (3–10 years).",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "NE",
    state_name: "Nebraska",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: false,
    expungement_notes: null,
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "ND",
    state_name: "North Dakota",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: false,
    expungement_notes: null,
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "SD",
    state_name: "South Dakota",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: false,
    expungement_notes: null,
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "MN",
    state_name: "Minnesota",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Minnesota Human Rights Act amendment",
    lookback_limit_years: null,
    lookback_limit_notes: "Criminal history inquiry deferred until applicant has been selected for interview or received conditional offer.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Minnesota allows expungement for many offenses including petty misdemeanors and some felonies.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "MT",
    state_name: "Montana",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: false,
    expungement_notes: null,
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "WY",
    state_name: "Wyoming",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: false,
    expungement_notes: null,
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "ID",
    state_name: "Idaho",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: false,
    expungement_notes: null,
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "UT",
    state_name: "Utah",
    has_ban_the_box: true,
    ban_the_box_scope: "public_only",
    ban_the_box_law_name: "Utah HB 156",
    lookback_limit_years: null,
    lookback_limit_notes: "State government employers only.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Utah allows expungement after waiting periods (3–10 years depending on offense).",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "AK",
    state_name: "Alaska",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: false,
    expungement_notes: null,
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "AL",
    state_name: "Alabama",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban. Birmingham has a local ordinance.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Alabama allows expungement for non-violent first offenses after 90 days from dismissal or acquittal.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "AR",
    state_name: "Arkansas",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Arkansas allows expungement for most non-violent offenses after waiting periods.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "DE",
    state_name: "Delaware",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Delaware Opportunity for Employment Act",
    lookback_limit_years: null,
    lookback_limit_notes: "Employers with 4+ employees cannot ask about criminal history until conditional offer stage.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Delaware allows expungement for misdemeanors after 5 years and some felonies after 7 years.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "ME",
    state_name: "Maine",
    has_ban_the_box: true,
    ban_the_box_scope: "all_employers",
    ban_the_box_law_name: "Maine Fair Chance in Employment Act",
    lookback_limit_years: null,
    lookback_limit_notes: "Criminal history inquiry deferred until conditional offer stage.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: false,
    expungement_notes: null,
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "NH",
    state_name: "New Hampshire",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "New Hampshire allows annulment of criminal records after waiting periods.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "MS",
    state_name: "Mississippi",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Mississippi allows expungement for first-time non-violent offenders after 5 years.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "WV",
    state_name: "West Virginia",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "West Virginia allows expungement for first-time non-violent offenders.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
  {
    state_code: "OK",
    state_name: "Oklahoma",
    has_ban_the_box: false,
    ban_the_box_scope: "none",
    ban_the_box_law_name: null,
    lookback_limit_years: null,
    lookback_limit_notes: "No statewide ban.",
    requires_individual_assessment: false,
    allows_expungement_nondisclosure: true,
    expungement_notes: "Oklahoma allows expungement for many non-violent offenses after waiting periods. SQ 805 (2020) reduced felony sentences.",
    credit_check_restricted: false,
    credit_check_notes: null,
    last_updated: "2024-01-01",
  },
]

async function run() {
  const connectionString = process.env.DATABASE_URL ?? process.env.TARGET_POSTGRES_URL
  if (!connectionString) throw new Error("DATABASE_URL is required")

  const pool = new Pool({ connectionString, ssl: process.env.NODE_ENV === "production" ? { rejectUnauthorized: false } : undefined })

  // Deduplicate by state_code (MN appeared twice in raw data above)
  const seen = new Set<string>()
  const uniqueStates = STATES.filter(s => {
    if (seen.has(s.state_code)) return false
    seen.add(s.state_code)
    return true
  })

  console.log(`Seeding ${uniqueStates.length} states...`)

  if (dryRun) {
    console.log("Dry run — would insert:", uniqueStates.map(s => s.state_code).join(", "))
    await pool.end()
    return
  }

  for (const s of uniqueStates) {
    await pool.query(
      `INSERT INTO public.state_protections (
        state_code, state_name, has_ban_the_box, ban_the_box_scope,
        ban_the_box_law_name, lookback_limit_years, lookback_limit_notes,
        requires_individual_assessment, allows_expungement_nondisclosure,
        expungement_notes, credit_check_restricted, credit_check_notes, last_updated
      ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
      ON CONFLICT (state_code) DO UPDATE SET
        state_name = EXCLUDED.state_name,
        has_ban_the_box = EXCLUDED.has_ban_the_box,
        ban_the_box_scope = EXCLUDED.ban_the_box_scope,
        ban_the_box_law_name = EXCLUDED.ban_the_box_law_name,
        lookback_limit_years = EXCLUDED.lookback_limit_years,
        lookback_limit_notes = EXCLUDED.lookback_limit_notes,
        requires_individual_assessment = EXCLUDED.requires_individual_assessment,
        allows_expungement_nondisclosure = EXCLUDED.allows_expungement_nondisclosure,
        expungement_notes = EXCLUDED.expungement_notes,
        credit_check_restricted = EXCLUDED.credit_check_restricted,
        credit_check_notes = EXCLUDED.credit_check_notes,
        last_updated = EXCLUDED.last_updated`,
      [
        s.state_code, s.state_name, s.has_ban_the_box, s.ban_the_box_scope,
        s.ban_the_box_law_name, s.lookback_limit_years, s.lookback_limit_notes,
        s.requires_individual_assessment, s.allows_expungement_nondisclosure,
        s.expungement_notes, s.credit_check_restricted, s.credit_check_notes,
        s.last_updated,
      ]
    )
    console.log(`  ✓ ${s.state_code} — ${s.state_name}`)
  }

  console.log(`\nSeeded ${uniqueStates.length} states successfully.`)
  await pool.end()
}

run().catch(err => {
  console.error(err)
  process.exit(1)
})
